# WORDS LIST FOR MY HANGMAN GAME


words = [
    "apple", "mango", "banana", "orange", "grapes", "kiwi", "papaya", "guava", "peach", "pear",
    "plum", "melon", "berry", "cherry", "lemon", "lime", "coconut", "apricot", "fig", "date",
    "carrot", "potato", "tomato", "onion", "garlic", "ginger", "radish", "turnip", "cabbage", "spinach",
    "broccoli", "lettuce", "celery", "pepper", "pumpkin", "beetroot", "pea", "bean", "corn", "okra",
    "school", "college", "teacher", "student", "pencil", "eraser", "notebook", "marker", "library", "subject",
    "english", "science", "history", "geography", "algebra", "physics", "biology", "chemistry", "grammar", "drawing",
    "computer", "laptop", "keyboard", "monitor", "printer", "scanner", "speaker", "router", "internet", "software",
    "hardware", "browser", "python", "java", "coding", "program", "network", "server", "screen", "mouse",
    "doctor", "nurse", "farmer", "lawyer", "engineer", "pilot", "driver", "artist", "singer", "dancer",
    "writer", "actor", "chef", "tailor", "barber", "manager", "worker", "plumber", "carpenter", "mechanic",
    "tiger", "lion", "zebra", "rabbit", "monkey", "donkey", "horse", "camel", "panda", "koala",
    "giraffe", "elephant", "cheetah", "wolf", "fox", "bear", "deer", "otter", "badger", "kangaroo",
    "parrot", "pigeon", "eagle", "falcon", "sparrow", "crow", "peacock", "ostrich", "penguin", "owl",
    "shark", "whale", "dolphin", "octopus", "lobster", "shrimp", "salmon", "trout", "turtle", "crab",
    "india", "canada", "brazil", "france", "germany", "italy", "spain", "china", "japan", "nepal",
    "bhutan", "russia", "mexico", "egypt", "turkey", "sweden", "norway", "finland", "argentina", "chile",
    "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday", "january", "february", "march",
    "april", "may", "june", "july", "august", "september", "october", "november", "december", "holiday",
    "cricket", "football", "hockey", "tennis", "badminton", "volleyball", "kabaddi", "golf", "boxing", "cycling",
    "running", "swimming", "wrestling", "archery", "karate", "baseball", "rugby", "skating", "surfing", "rowing",
    "happy", "angry", "brave", "calm", "clever", "honest", "kind", "loyal", "proud", "smart",
    "strong", "gentle", "quiet", "friendly", "funny", "active", "eager", "famous", "jolly", "polite",
    "house", "window", "kitchen", "garden", "bedroom", "ceiling", "mirror", "curtain", "balcony", "stairs",
    "sofa", "table", "chair", "drawer", "cupboard", "blanket", "pillow", "mattress", "carpet", "lamp",
    "train", "station", "airport", "bicycle", "scooter", "bus", "truck", "helmet", "signal", "bridge",
    "tunnel", "highway", "garage", "engine", "diesel", "petrol", "driver", "ticket", "travel", "journey",
    "music", "guitar", "violin", "piano", "drums", "flute", "trumpet", "melody", "rhythm", "concert",
    "movie", "camera", "screenplay", "director", "cinema", "drama", "comedy", "action", "romance", "thriller",
    "cloud", "thunder", "rainbow", "sunshine", "breeze", "storm", "winter", "summer", "autumn", "spring",
    "desert", "forest", "island", "mountain", "valley", "river", "ocean", "beach", "waterfall", "volcano",
    "gold", "silver", "copper", "diamond", "marble", "granite", "plastic", "rubber", "cotton", "leather",
    "shirt", "trouser", "jacket", "sweater", "sandal", "slipper", "gloves", "helmet", "wallet", "pocket",
    "breakfast", "lunch", "dinner", "snacks", "sandwich", "burger", "pizza", "noodles", "pasta", "biscuit",
    "coffee", "tea", "juice", "sugar", "butter", "cheese", "yogurt", "pickle", "salad", "soup",
    "planet", "galaxy", "rocket", "saturn", "venus", "mercury", "jupiter", "comet", "asteroid", "meteor",
    "energy", "gravity", "oxygen", "carbon", "nitrogen", "battery", "circuit", "magnet", "engineer", "machine",
    "friend", "family", "mother", "father", "brother", "sister", "uncle", "aunt", "cousin", "nephew",
    "baby", "child", "adult", "people", "person", "citizen", "neighbor", "partner", "leader", "hero",
    "market", "shop", "mall", "vendor", "seller", "buyer", "basket", "packet", "bottle", "carton",
    "clock", "watch", "minute", "second", "future", "past", "present", "moment", "memory", "dream",
    "victory", "success", "failure", "problem", "answer", "question", "chance", "choice", "effort", "result",
    "beauty", "nature", "wisdom", "honor", "peace", "truth", "freedom", "justice", "respect", "spirit"
]